# Generated by Django 5.2.6 on 2025-09-07 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_id", models.CharField(max_length=100)),
                ("event_type", models.CharField(max_length=50)),
                ("headers", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=dict)),
                ("processing_result", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="received", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regfox_order_id", models.CharField(blank=True, max_length=100)),
                ("regfox_registrant_id", models.CharField(blank=True, max_length=100)),
                ("regfox_order_number", models.CharField(blank=True, max_length=100)),
                ("regfox_customer_id", models.CharField(blank=True, max_length=100)),
                (
                    "registration_status",
                    models.CharField(default="pending", max_length=50),
                ),
                ("raw_registration_data", models.JSONField(blank=True, default=dict)),
                ("raw_billing_data", models.JSONField(blank=True, default=dict)),
                ("registration_timestamp", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration Data",
                "verbose_name_plural": "Registration Data",
            },
        ),
    ]
